#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/docker_images

matrix:
  include:

  # The Warm up stage is used to generate the ubertools docker image for building.
  - stage: Warmup
    language: generic
    script: "if [ -x ./.travis/warmup-script.sh   ] ; then ./.travis/warmup-script.sh ; fi"

  # The build stages will have the ubertools docker image in the docker build cache.
  - stage: avro-builds
    name: Build the world with JAVA=8
    language: generic
    script: "JAVA=8 ./.travis/script.sh"
  - name: Build the world with JAVA=11
    language: generic
    script: "JAVA=11 ./.travis/script.sh"
  - os: windows
    language: bash

before_install: "if [ -x ./.travis/before_install.sh   ] ; then ./.travis/before_install.sh ; fi"
install:        "if [ -x ./.travis/install.sh          ] ; then ./.travis/install.sh        ; fi"
before_script:  "if [ -x ./.travis/before_script.sh    ] ; then ./.travis/before_script.sh  ; fi"
script:         "if [ -x ./.travis/script.sh           ] ; then ./.travis/script.sh         ; fi"
after_script:   "if [ -x ./.travis/after_script.sh     ] ; then ./.travis/after_script.sh   ; fi"
before_cache:   "if [ -x ./.travis/before_cache.sh     ] ; then ./.travis/before_cache.sh   ; fi"
